# Generated by Django 4.1 on 2022-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('near', '0003_delete_mesure_alter_coordonnees_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnees',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='coordonnees',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
